### ISSUE TITLE
Can you add output variables

### ISSUE THREAD

**Issue by hamelsmu** [marvinbuss/MLDevOps#1]
Hi @marvinbuss I'm working with @aronchick at GitHub.  We saw your [cool example of CI/CD](https://github.com/marvinbuss/MLDevOps/blob/master/.github/workflows/azureml-ci-cd.yml), one thing that would help us demo a cool integration is in each of your python pipeline steps, can you emit the following output variables 

- `dashboard_link` example:  `https://something.aml.com/your_dashboard/training`
- `runtime`: something formatted in hours, example `1h2m`
- `commit_sha`: the commit sha that corresponds to the which code in GitHub that the step was run on

You can emit output variables with [this syntax](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions)

```yaml
print("::set-output name=action_fruit::strawberry")
```  

For example to emit the output variable `dashboard_link` you would do the following
```yaml
print("::set-output name=label_name::https://something.aml.com/your_dashboard/training")
```

The idea is we could report back status upon the successful completion of each step into the PR with a link to the results.   You might know better than us where to get the links (if available) as I am not familiar with Azure.   Thanks would really love to use this workflow in an upcoming demo!

cc: @T-holland, @inc0, @awmatheson

**Comment by marvinbuss** [comment]
Hi @hamelsmu,
Hi @aronchick,
thanks for your message. I am happy to help you, but I probably need some time, since I am travelling all week. I will send you a DM, to discuss further details. When do you want to demo the CI/CD example?

**Comment by hamelsmu** [comment]
Sometime towards the end of the month, probably.  I think your example
might be almost there except the reporting back to GitHub which I’m hoping
is easy to pull off
